export interface CostItem {
  id: string;
  label: string;
  min: number; // in USD
  max: number; // in USD
  category: "Before Departure" | "First 6 Months";
  description: string;
}

export const COUNTRY_COSTS_DATA: Record<string, CostItem[]> = {
  US: [
    { id: "passport", label: "Passport", min: 45, max: 90, category: "Before Departure", description: "Passport issuance fees in Nepal" },
    { id: "visa", label: "Student Visa", min: 185, max: 185, category: "Before Departure", description: "F-1 student visa application fee" },
    { id: "sevis", label: "SEVIS Fee", min: 350, max: 350, category: "Before Departure", description: "Mandatory Student and Exchange Visitor program fee" },
    { id: "app-fees", label: "University Application Fees", min: 50, max: 150, category: "Before Departure", description: "Target university application/processing fees" },
    { id: "exams", label: "IELTS / TOEFL / Duolingo", min: 65, max: 250, category: "Before Departure", description: "English proficiency test exam fees" },
    { id: "translation", label: "Document Translation", min: 20, max: 100, category: "Before Departure", description: "Academic certificate translation & notarization" },
    { id: "medical", label: "Medical Examination", min: 80, max: 250, category: "Before Departure", description: "Mandatory student medical screening" },
    { id: "vaccines", label: "Vaccinations", min: 30, max: 200, category: "Before Departure", description: "Immunization records and health validation" },
    { id: "health-insurance-init", label: "Initial Health Insurance", min: 300, max: 1500, category: "Before Departure", description: "Health cover required prior to departure" },
    { id: "flight", label: "Flight Ticket", min: 800, max: 1800, category: "Before Departure", description: "One-way flight from Kathmandu to destination" },
    { id: "airport-transport", label: "Airport Transportation", min: 10, max: 50, category: "Before Departure", description: "Initial travel from arrival airport to housing" },
    { id: "baggage", label: "Extra Baggage", min: 50, max: 250, category: "Before Departure", description: "Additional luggage allowance fees" },
    { id: "acc-deposit", label: "Accommodation Deposit", min: 500, max: 2000, category: "Before Departure", description: "Advance reservation deposit for student housing" },
    { id: "sec-deposit", label: "Security Deposit", min: 500, max: 2000, category: "Before Departure", description: "Refundable damage deposit for landlord" },
    { id: "rent-1", label: "First Month Rent", min: 700, max: 2500, category: "Before Departure", description: "First month rental payment in advance" },
    { id: "bank-setup", label: "Bank Setup", min: 10, max: 50, category: "Before Departure", description: "Account opening charges and cards" },
    { id: "sim", label: "SIM/eSIM", min: 10, max: 40, category: "Before Departure", description: "Local cellular SIM and activation" },
    { id: "travel-insurance", label: "Travel Insurance", min: 50, max: 200, category: "Before Departure", description: "Temporary transit travel insurance cover" },
    { id: "misc-dep", label: "Miscellaneous departure costs", min: 100, max: 500, category: "Before Departure", description: "Unforeseen transit and setup expenses" },
    { id: "shopping-dep", label: "Before Departure Shopping", min: 300, max: 800, category: "Before Departure", description: "Luggage bags, clothing, adapters, and essentials" },
    // 6 Months
    { id: "accommodation", label: "Accommodation", min: 4800, max: 12000, category: "First 6 Months", description: "Student accommodation or shared apartment rental" },
    { id: "utilities", label: "Utilities", min: 480, max: 1200, category: "First 6 Months", description: "Gas, electricity, water, and heating bills" },
    { id: "internet", label: "Internet", min: 240, max: 480, category: "First 6 Months", description: "Student broadband WiFi connection" },
    { id: "mobile", label: "Mobile Phone", min: 180, max: 420, category: "First 6 Months", description: "Monthly mobile network bills" },
    { id: "food", label: "Food & Groceries", min: 1800, max: 4200, category: "First 6 Months", description: "Groceries, pantry staples, and cooking supplies" },
    { id: "transport", label: "Transportation", min: 300, max: 1200, category: "First 6 Months", description: "Student subway/bus cards and daily commute" },
    { id: "insurance", label: "Health Insurance", min: 600, max: 1800, category: "First 6 Months", description: "Premium student healthcare coverage" },
    { id: "books", label: "Books & Study Materials", min: 300, max: 900, category: "First 6 Months", description: "Reference textbooks, printing, and stationeries" },
    { id: "personal", label: "Personal Expenses", min: 600, max: 1800, category: "First 6 Months", description: "Hygiene, clothing updates, and daily essentials" },
    { id: "entertainment", label: "Entertainment", min: 300, max: 1200, category: "First 6 Months", description: "Dinings, cafes, weekend getaways, and gym" },
    { id: "laundry", label: "Laundry", min: 120, max: 300, category: "First 6 Months", description: "Washing, drying, and laundry items" },
    { id: "misc-living", label: "Miscellaneous living expenses", min: 300, max: 1200, category: "First 6 Months", description: "Emergency fund reserves" },
  ],
  CA: [
    { id: "passport", label: "Passport", min: 45, max: 90, category: "Before Departure", description: "Passport issuance fees in Nepal" },
    { id: "permit", label: "Study Permit", min: 110, max: 180, category: "Before Departure", description: "Canada Study Permit application fee" },
    { id: "biometrics", label: "Biometrics", min: 65, max: 90, category: "Before Departure", description: "Visa center biometrics capture fee" },
    { id: "exams", label: "IELTS / PTE", min: 65, max: 250, category: "Before Departure", description: "Language test registration fee" },
    { id: "medical", label: "Medical Examination", min: 100, max: 250, category: "Before Departure", description: "Mandatory student medical screening" },
    { id: "flight", label: "Flight Ticket", min: 900, max: 1900, category: "Before Departure", description: "One-way flight ticket from Kathmandu to Canada" },
    { id: "health-insurance-init", label: "Health Insurance", min: 300, max: 900, category: "Before Departure", description: "Initial health cover prior to departure" },
    { id: "acc-deposit", label: "Accommodation Deposit", min: 700, max: 2000, category: "Before Departure", description: "Advance reservation deposit for student housing" },
    { id: "sec-deposit", label: "Security Deposit", min: 700, max: 2000, category: "Before Departure", description: "Refundable security deposit for landlord" },
    { id: "rent-1", label: "First Month Rent", min: 700, max: 1800, category: "Before Departure", description: "First month rental payment in advance" },
    { id: "travel-insurance", label: "Travel Insurance", min: 50, max: 200, category: "Before Departure", description: "Temporary transit travel insurance cover" },
    { id: "sim", label: "SIM/eSIM", min: 10, max: 40, category: "Before Departure", description: "Local SIM card activation" },
    { id: "misc-dep", label: "Miscellaneous departure costs", min: 100, max: 400, category: "Before Departure", description: "Unforeseen transit and setup expenses" },
    { id: "shopping-dep", label: "Before Departure Shopping", min: 300, max: 800, category: "Before Departure", description: "Luggage bags, clothing, adapters, and essentials" },
    // 6 Months
    { id: "accommodation", label: "Accommodation", min: 4200, max: 10800, category: "First 6 Months", description: "Student accommodation or shared apartment rental" },
    { id: "utilities", label: "Utilities", min: 420, max: 1080, category: "First 6 Months", description: "Gas, electricity, water, and heating bills" },
    { id: "internet", label: "Internet", min: 270, max: 480, category: "First 6 Months", description: "Student broadband WiFi connection" },
    { id: "mobile", label: "Mobile Phone", min: 210, max: 420, category: "First 6 Months", description: "Monthly mobile network bills" },
    { id: "food", label: "Food & Groceries", min: 1500, max: 3600, category: "First 6 Months", description: "Groceries, pantry staples, and cooking supplies" },
    { id: "transport", label: "Transportation", min: 360, max: 900, category: "First 6 Months", description: "Student subway/bus cards and daily commute" },
    { id: "insurance", label: "Health Insurance", min: 300, max: 900, category: "First 6 Months", description: "Premium student healthcare coverage" },
    { id: "books", label: "Books & Study Materials", min: 300, max: 720, category: "First 6 Months", description: "Reference textbooks, printing, and stationeries" },
    { id: "personal", label: "Personal Expenses", min: 480, max: 1500, category: "First 6 Months", description: "Hygiene, clothing updates, and daily essentials" },
    { id: "entertainment", label: "Entertainment", min: 300, max: 1080, category: "First 6 Months", description: "Dinings, cafes, weekend getaways, and gym" },
    { id: "laundry", label: "Laundry", min: 120, max: 240, category: "First 6 Months", description: "Washing, drying, and laundry items" },
    { id: "misc-living", label: "Miscellaneous living expenses", min: 300, max: 1080, category: "First 6 Months", description: "Emergency fund reserves" },
  ],
  AU: [
    { id: "passport", label: "Passport", min: 45, max: 90, category: "Before Departure", description: "Passport issuance fees in Nepal" },
    { id: "visa", label: "Student Visa", min: 1100, max: 1300, category: "Before Departure", description: "Australia Student Visa application fee" },
    { id: "exams", label: "IELTS / PTE", min: 65, max: 250, category: "Before Departure", description: "Language test registration fee" },
    { id: "medical", label: "Medical Examination", min: 120, max: 300, category: "Before Departure", description: "Mandatory student medical screening" },
    { id: "health-insurance-init", label: "OSHC Health Cover", min: 400, max: 900, category: "Before Departure", description: "Overseas Student Health Cover required prior to departure" },
    { id: "flight", label: "Flight Ticket", min: 700, max: 1600, category: "Before Departure", description: "One-way flight ticket from Kathmandu to Australia" },
    { id: "acc-deposit", label: "Accommodation Deposit", min: 800, max: 2000, category: "Before Departure", description: "Advance reservation deposit for student housing" },
    { id: "sec-deposit", label: "Security Deposit", min: 800, max: 2000, category: "Before Departure", description: "Refundable security deposit for landlord" },
    { id: "rent-1", label: "First Month Rent", min: 900, max: 2000, category: "Before Departure", description: "First month rental payment in advance" },
    { id: "travel-insurance", label: "Travel Insurance", min: 50, max: 200, category: "Before Departure", description: "Temporary transit travel insurance cover" },
    { id: "sim", label: "SIM/eSIM", min: 10, max: 40, category: "Before Departure", description: "Local SIM card activation" },
    { id: "misc-dep", label: "Miscellaneous departure costs", min: 100, max: 500, category: "Before Departure", description: "Unforeseen transit and setup expenses" },
    { id: "shopping-dep", label: "Before Departure Shopping", min: 300, max: 800, category: "Before Departure", description: "Luggage bags, clothing, adapters, and essentials" },
    // 6 Months
    { id: "accommodation", label: "Accommodation", min: 5400, max: 13200, category: "First 6 Months", description: "Student accommodation or shared apartment rental" },
    { id: "utilities", label: "Utilities", min: 480, max: 1200, category: "First 6 Months", description: "Gas, electricity, water, and heating bills" },
    { id: "internet", label: "Internet", min: 300, max: 480, category: "First 6 Months", description: "Student broadband WiFi connection" },
    { id: "mobile", label: "Mobile Phone", min: 150, max: 360, category: "First 6 Months", description: "Monthly mobile network bills" },
    { id: "food", label: "Food & Groceries", min: 1800, max: 4200, category: "First 6 Months", description: "Groceries, pantry staples, and cooking supplies" },
    { id: "transport", label: "Transportation", min: 360, max: 1080, category: "First 6 Months", description: "Student subway/bus cards and daily commute" },
    { id: "insurance", label: "Health Insurance", min: 300, max: 720, category: "First 6 Months", description: "Premium student healthcare coverage" },
    { id: "books", label: "Books & Study Materials", min: 300, max: 900, category: "First 6 Months", description: "Reference textbooks, printing, and stationeries" },
    { id: "personal", label: "Personal Expenses", min: 600, max: 1800, category: "First 6 Months", description: "Hygiene, clothing updates, and daily essentials" },
    { id: "entertainment", label: "Entertainment", min: 480, max: 1500, category: "First 6 Months", description: "Dinings, cafes, weekend getaways, and gym" },
    { id: "laundry", label: "Laundry", min: 120, max: 300, category: "First 6 Months", description: "Washing, drying, and laundry items" },
    { id: "misc-living", label: "Miscellaneous living expenses", min: 480, max: 1500, category: "First 6 Months", description: "Emergency fund reserves" },
  ],
  GB: [
    { id: "passport", label: "Passport", min: 45, max: 90, category: "Before Departure", description: "Passport issuance fees in Nepal" },
    { id: "visa", label: "Student Visa", min: 650, max: 750, category: "Before Departure", description: "UK Student Visa application fee" },
    { id: "ihs", label: "Immigration Health Surcharge", min: 900, max: 1500, category: "Before Departure", description: "Mandatory NHS healthcare surcharge" },
    { id: "exams", label: "IELTS", min: 65, max: 250, category: "Before Departure", description: "Language test registration fee" },
    { id: "medical", label: "Medical Examination", min: 80, max: 250, category: "Before Departure", description: "Mandatory student medical screening" },
    { id: "flight", label: "Flight Ticket", min: 700, max: 1500, category: "Before Departure", description: "One-way flight ticket from Kathmandu to UK" },
    { id: "acc-deposit", label: "Accommodation Deposit", min: 800, max: 2000, category: "Before Departure", description: "Advance reservation deposit for student housing" },
    { id: "sec-deposit", label: "Security Deposit", min: 800, max: 2000, category: "Before Departure", description: "Refundable security deposit for landlord" },
    { id: "rent-1", label: "First Month Rent", min: 900, max: 2000, category: "Before Departure", description: "First month rental payment in advance" },
    { id: "travel-insurance", label: "Travel Insurance", min: 50, max: 200, category: "Before Departure", description: "Temporary transit travel insurance cover" },
    { id: "sim", label: "SIM/eSIM", min: 10, max: 40, category: "Before Departure", description: "Local SIM card activation" },
    { id: "misc-dep", label: "Miscellaneous departure costs", min: 100, max: 400, category: "Before Departure", description: "Unforeseen transit and setup expenses" },
    { id: "shopping-dep", label: "Before Departure Shopping", min: 300, max: 800, category: "Before Departure", description: "Luggage bags, clothing, adapters, and essentials" },
    // 6 Months
    { id: "accommodation", label: "Accommodation", min: 5400, max: 12000, category: "First 6 Months", description: "Student accommodation or shared apartment rental" },
    { id: "utilities", label: "Utilities", min: 600, max: 1500, category: "First 6 Months", description: "Gas, electricity, water, and heating bills" },
    { id: "internet", label: "Internet", min: 210, max: 420, category: "First 6 Months", description: "Student broadband WiFi connection" },
    { id: "mobile", label: "Mobile Phone", min: 120, max: 300, category: "First 6 Months", description: "Monthly mobile network bills" },
    { id: "food", label: "Food & Groceries", min: 1800, max: 4200, category: "First 6 Months", description: "Groceries, pantry staples, and cooking supplies" },
    { id: "transport", label: "Transportation", min: 480, max: 1320, category: "First 6 Months", description: "Student subway/bus cards and daily commute" },
    { id: "books", label: "Books & Study Materials", min: 240, max: 720, category: "First 6 Months", description: "Reference textbooks, printing, and stationeries" },
    { id: "personal", label: "Personal Expenses", min: 600, max: 1800, category: "First 6 Months", description: "Hygiene, clothing updates, and daily essentials" },
    { id: "entertainment", label: "Entertainment", min: 420, max: 1500, category: "First 6 Months", description: "Dinings, cafes, weekend getaways, and gym" },
    { id: "laundry", label: "Laundry", min: 120, max: 300, category: "First 6 Months", description: "Washing, drying, and laundry items" },
    { id: "misc-living", label: "Miscellaneous living expenses", min: 360, max: 1200, category: "First 6 Months", description: "Emergency fund reserves" },
  ],
  IE: [
    { id: "passport", label: "Passport", min: 45, max: 90, category: "Before Departure", description: "Passport issuance fees in Nepal" },
    { id: "visa", label: "Student Visa", min: 65, max: 120, category: "Before Departure", description: "Ireland Student Visa application fee" },
    { id: "exams", label: "IELTS", min: 65, max: 250, category: "Before Departure", description: "Language test registration fee" },
    { id: "medical", label: "Medical Examination", min: 80, max: 250, category: "Before Departure", description: "Mandatory student medical screening" },
    { id: "health-insurance-init", label: "Health Insurance", min: 250, max: 700, category: "Before Departure", description: "Initial health cover prior to departure" },
    { id: "flight", label: "Flight Ticket", min: 700, max: 1600, category: "Before Departure", description: "One-way flight ticket from Kathmandu to Ireland" },
    { id: "acc-deposit", label: "Accommodation Deposit", min: 800, max: 2000, category: "Before Departure", description: "Advance reservation deposit for student housing" },
    { id: "sec-deposit", label: "Security Deposit", min: 800, max: 2000, category: "Before Departure", description: "Refundable security deposit for landlord" },
    { id: "rent-1", label: "First Month Rent", min: 900, max: 2000, category: "Before Departure", description: "First month rental payment in advance" },
    { id: "travel-insurance", label: "Travel Insurance", min: 50, max: 200, category: "Before Departure", description: "Temporary transit travel insurance cover" },
    { id: "sim", label: "SIM/eSIM", min: 10, max: 40, category: "Before Departure", description: "Local SIM card activation" },
    { id: "misc-dep", label: "Miscellaneous departure costs", min: 100, max: 400, category: "Before Departure", description: "Unforeseen transit and setup expenses" },
    { id: "shopping-dep", label: "Before Departure Shopping", min: 300, max: 800, category: "Before Departure", description: "Luggage bags, clothing, adapters, and essentials" },
    // 6 Months
    { id: "accommodation", label: "Accommodation", min: 5400, max: 12000, category: "First 6 Months", description: "Student accommodation or shared apartment rental" },
    { id: "utilities", label: "Utilities", min: 600, max: 1320, category: "First 6 Months", description: "Gas, electricity, water, and heating bills" },
    { id: "internet", label: "Internet", min: 240, max: 420, category: "First 6 Months", description: "Student broadband WiFi connection" },
    { id: "mobile", label: "Mobile Phone", min: 120, max: 300, category: "First 6 Months", description: "Monthly mobile network bills" },
    { id: "food", label: "Food & Groceries", min: 1800, max: 3900, category: "First 6 Months", description: "Groceries, pantry staples, and cooking supplies" },
    { id: "transport", label: "Transportation", min: 420, max: 1080, category: "First 6 Months", description: "Student subway/bus cards and daily commute" },
    { id: "insurance", label: "Health Insurance", min: 240, max: 720, category: "First 6 Months", description: "Premium student healthcare coverage" },
    { id: "books", label: "Books & Study Materials", min: 240, max: 600, category: "First 6 Months", description: "Reference textbooks, printing, and stationeries" },
    { id: "personal", label: "Personal Expenses", min: 600, max: 1500, category: "First 6 Months", description: "Hygiene, clothing updates, and daily essentials" },
    { id: "entertainment", label: "Entertainment", min: 420, max: 1200, category: "First 6 Months", description: "Dinings, cafes, weekend getaways, and gym" },
    { id: "laundry", label: "Laundry", min: 120, max: 300, category: "First 6 Months", description: "Washing, drying, and laundry items" },
    { id: "misc-living", label: "Miscellaneous living expenses", min: 360, max: 1080, category: "First 6 Months", description: "Emergency fund reserves" },
  ],
  DE: [
    { id: "passport", label: "Passport", min: 45, max: 90, category: "Before Departure", description: "Passport issuance fees in Nepal" },
    { id: "visa", label: "Student Visa", min: 80, max: 120, category: "Before Departure", description: "Germany Student Visa application fee" },
    { id: "aps", label: "APS Certificate", min: 100, max: 250, category: "Before Departure", description: "Academic evaluation center (APS) certificate" },
    { id: "exams", label: "IELTS / TestDaF", min: 65, max: 250, category: "Before Departure", description: "Language test registration fee" },
    { id: "medical", label: "Medical Examination", min: 80, max: 250, category: "Before Departure", description: "Mandatory student medical screening" },
    { id: "health-insurance-init", label: "Health Insurance", min: 150, max: 500, category: "Before Departure", description: "Initial health cover prior to departure" },
    { id: "flight", label: "Flight Ticket", min: 700, max: 1500, category: "Before Departure", description: "One-way flight ticket from Kathmandu to Germany" },
    { id: "acc-deposit", label: "Accommodation Deposit", min: 700, max: 2000, category: "Before Departure", description: "Advance reservation deposit for student housing" },
    { id: "sec-deposit", label: "Security Deposit", min: 700, max: 2000, category: "Before Departure", description: "Refundable security deposit for landlord" },
    { id: "rent-1", label: "First Month Rent", min: 700, max: 1500, category: "Before Departure", description: "First month rental payment in advance" },
    { id: "travel-insurance", label: "Travel Insurance", min: 50, max: 200, category: "Before Departure", description: "Temporary transit travel insurance cover" },
    { id: "sim", label: "SIM/eSIM", min: 10, max: 40, category: "Before Departure", description: "Local SIM card activation" },
    { id: "misc-dep", label: "Miscellaneous departure costs", min: 100, max: 400, category: "Before Departure", description: "Unforeseen transit and setup expenses" },
    { id: "shopping-dep", label: "Before Departure Shopping", min: 300, max: 800, category: "Before Departure", description: "Luggage bags, clothing, adapters, and essentials" },
    // 6 Months
    { id: "accommodation", label: "Accommodation", min: 3600, max: 8400, category: "First 6 Months", description: "Student accommodation or shared apartment rental" },
    { id: "utilities", label: "Utilities", min: 600, max: 1320, category: "First 6 Months", description: "Gas, electricity, water, and heating bills" },
    { id: "internet", label: "Internet", min: 210, max: 360, category: "First 6 Months", description: "Student broadband WiFi connection" },
    { id: "mobile", label: "Mobile Phone", min: 120, max: 240, category: "First 6 Months", description: "Monthly mobile network bills" },
    { id: "food", label: "Food & Groceries", min: 1500, max: 3000, category: "First 6 Months", description: "Groceries, pantry staples, and cooking supplies" },
    { id: "transport", label: "Transportation", min: 240, max: 600, category: "First 6 Months", description: "Student subway/bus cards and daily commute" },
    { id: "insurance", label: "Health Insurance", min: 720, max: 1080, category: "First 6 Months", description: "Premium student healthcare coverage" },
    { id: "books", label: "Books & Study Materials", min: 180, max: 600, category: "First 6 Months", description: "Reference textbooks, printing, and stationeries" },
    { id: "personal", label: "Personal Expenses", min: 480, max: 1200, category: "First 6 Months", description: "Hygiene, clothing updates, and daily essentials" },
    { id: "entertainment", label: "Entertainment", min: 300, max: 900, category: "First 6 Months", description: "Dinings, cafes, weekend getaways, and gym" },
    { id: "laundry", label: "Laundry", min: 120, max: 240, category: "First 6 Months", description: "Washing, drying, and laundry items" },
    { id: "misc-living", label: "Miscellaneous living expenses", min: 300, max: 900, category: "First 6 Months", description: "Emergency fund reserves" },
  ],
  MT: [
    { id: "passport", label: "Passport", min: 45, max: 90, category: "Before Departure", description: "Passport issuance fees in Nepal" },
    { id: "visa", label: "Student Visa", min: 80, max: 150, category: "Before Departure", description: "Malta Student Visa application fee" },
    { id: "exams", label: "IELTS", min: 65, max: 250, category: "Before Departure", description: "Language test registration fee" },
    { id: "medical", label: "Medical Examination", min: 80, max: 250, category: "Before Departure", description: "Mandatory student medical screening" },
    { id: "health-insurance-init", label: "Health Insurance", min: 150, max: 500, category: "Before Departure", description: "Initial health cover prior to departure" },
    { id: "flight", label: "Flight Ticket", min: 600, max: 1300, category: "Before Departure", description: "One-way flight ticket from Kathmandu to Malta" },
    { id: "acc-deposit", label: "Accommodation Deposit", min: 500, max: 1500, category: "Before Departure", description: "Advance reservation deposit for student housing" },
    { id: "sec-deposit", label: "Security Deposit", min: 500, max: 1500, category: "Before Departure", description: "Refundable security deposit for landlord" },
    { id: "rent-1", label: "First Month Rent", min: 600, max: 1200, category: "Before Departure", description: "First month rental payment in advance" },
    { id: "travel-insurance", label: "Travel Insurance", min: 50, max: 200, category: "Before Departure", description: "Temporary transit travel insurance cover" },
    { id: "sim", label: "SIM/eSIM", min: 10, max: 30, category: "Before Departure", description: "Local SIM card activation" },
    { id: "misc-dep", label: "Miscellaneous departure costs", min: 100, max: 300, category: "Before Departure", description: "Unforeseen transit and setup expenses" },
    { id: "shopping-dep", label: "Before Departure Shopping", min: 300, max: 800, category: "Before Departure", description: "Luggage bags, clothing, adapters, and essentials" },
    // 6 Months
    { id: "accommodation", label: "Accommodation", min: 3600, max: 7200, category: "First 6 Months", description: "Student accommodation or shared apartment rental" },
    { id: "utilities", label: "Utilities", min: 420, max: 1080, category: "First 6 Months", description: "Gas, electricity, water, and heating bills" },
    { id: "internet", label: "Internet", min: 180, max: 300, category: "First 6 Months", description: "Student broadband WiFi connection" },
    { id: "mobile", label: "Mobile Phone", min: 90, max: 210, category: "First 6 Months", description: "Monthly mobile network bills" },
    { id: "food", label: "Food & Groceries", min: 1500, max: 3000, category: "First 6 Months", description: "Groceries, pantry staples, and cooking supplies" },
    { id: "transport", label: "Transportation", min: 180, max: 480, category: "First 6 Months", description: "Student subway/bus cards and daily commute" },
    { id: "insurance", label: "Health Insurance", min: 180, max: 480, category: "First 6 Months", description: "Premium student healthcare coverage" },
    { id: "books", label: "Books & Study Materials", min: 180, max: 480, category: "First 6 Months", description: "Reference textbooks, printing, and stationeries" },
    { id: "personal", label: "Personal Expenses", min: 480, max: 1200, category: "First 6 Months", description: "Hygiene, clothing updates, and daily essentials" },
    { id: "entertainment", label: "Entertainment", min: 300, max: 900, category: "First 6 Months", description: "Dinings, cafes, weekend getaways, and gym" },
    { id: "laundry", label: "Laundry", min: 120, max: 240, category: "First 6 Months", description: "Washing, drying, and laundry items" },
    { id: "misc-living", label: "Miscellaneous living expenses", min: 240, max: 720, category: "First 6 Months", description: "Emergency fund reserves" },
  ]
};
